### ISSUE TITLE
Add mobile mode

### ISSUE THREAD

**Issue by martinschierle** [GoogleChromeLabs/performance-game#1]
Add and implement a mobile mode:
* Add a way to control spaceship on mobile
* Make sure velocity of objects, size of objects etc. handles well on mobile (maybe factor out all of these into settings, so that we can have one mobile and one desktop settings file)

**Comment by martinschierle** [comment]
I added some missing viewport tags, now at least visually it looks better than before. We however still need mobile controls etc., so bulk of work here is still missing.

**Comment by martinschierle** [comment]
I added a manifest for PWA stuff, and set it to  force landscape...doesn't really seem to work though, at least not in emulator, probably only does something if started via homescreen icon

**Comment by martinschierle** [comment]
There's a nice example on how to use motion sensors with phaser here:

https://developer.mozilla.org/en-US/docs/Games/Tutorials/HTML5_Gamedev_Phaser_Device_Orientation

With this we'd only need to render a 'fire' button on top for mobile mode.
@cheneytsai  This is currently assigned to you - do you think you'll have time to work on this, otherwise I'd assign to me and wrap this up over holiday break?

**Comment by cheneytsai** [comment]
Oh sorry I forgot I had started to work on it. I never made meaningful
progress here and probably don't have the time for it.😥 Feel free to
reassign. Sorry!

**Comment by martinschierle** [comment]
No worries, thanks for looking into it! :-)

**Comment by martinschierle** [comment]
First draft is in. Some bugs and smaller things aren't perfect, but I will add specific issues for those.
