### ISSUE TITLE
Add PWA functionality

### ISSUE THREAD

**Issue by martinschierle** [GoogleChromeLabs/performance-game#10]
Make the game a real PWA (add manifest+sw). Probably this one goes together with adding real build chains etc.

**Comment by Svenmay** [comment]
I would like to ask some questions about this issue, just to make sure that I understand it correctly:

- Adding a SW shouldn't be too much of a problem, but what features of the PWA do we want to implement? A2HS seems to be useful, but e.g. "offline mode" or "advanced caching" is not, is it?
- Should we implement workbox, or just a plain SW?
- We would need some icons that can be referenced in the manifest file. Any preferences for the icon(s)? The sprite of the spaceship looks like a good candidate? Can we use that?

**Comment by martinschierle** [comment]
Just now seeing that you assigned this - sorry for missing it. I added a very basic default sw - not autogenerated, not optimized, but gives green PWA score in Lighthouse. Feel free to work from there or replace as needed!

**Comment by martinschierle** [comment]
Closing for now, as PWA basics work somewhat well so far.
