### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by martinschierle** [GoogleChromeLabs/performance-game#11]
Add in GA for games started, games won and lost, highscore and URL/host being played (we need to map this back at some point to see how many rey1k clients were among the games played)

**Comment by martinschierle** [comment]
Not sure if you just assigned this for testing or if you indeed wanna work on this, but either way - you can use this property and GA code:


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123358764-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123358764-1');
</script>

**Comment by antoinebisch** [comment]
Thanks martin. Will implement this :)

<https://www.google.com/doodles/44th-anniversary-of-the-birth-of-hip-hop>


*  •  **Antoine Bisch*
*  •  *Mobile Solutions Consultant
*  •  *1-13 St Giles High Street, WC2H 8AG, London
  •  antoinebisch@google.com

<antoinebisch@google.com>


This email may be confidential and privileged. If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it has gone
to the wrong person.

The above terms reflect a potential business arrangement, are provided
solely as a basis for further discussion, and are not intended to be and do
not constitute a legally binding obligation. No legally binding obligations
will be created, implied, or inferred until an agreement in final form is
executed in writing by all parties involved.

**Comment by martinschierle** [comment]
Thanks Antoine, merged your code in!

**Comment by martinschierle** [comment]
Closing for now
