### ISSUE TITLE
Add visual loading strip to game

### ISSUE THREAD

**Issue by martinschierle** [GoogleChromeLabs/performance-game#17]
Now that the backend works with lighthouse, we also get the nice visual loading strip of the page.
I'd suggest to show this at the bottom of the game, with a red marker indicating where you are playing at the moment. Not too high though, so that it doesn't take too much game space away

**Comment by martinschierle** [comment]
I already added a line to extract the data URL (?) for the visual loading bar in the server.js:

var lhr_screenshots = lhr.audits["screenshot-thumbnails"].details.items[0].data;
  
Not completely sure however if this is really a data URL and what it shows - probably needs some playing around with it.

**Comment by antoinebisch** [comment]
Hi Martin,

I am struggling to run the game. I get this error when I try launching it
(seems related to puppeteer):



Have you seen something similar before? Any idea how to bypass this?

Thank you.

<https://www.google.com/doodles/44th-anniversary-of-the-birth-of-hip-hop>


*  •  **Antoine Bisch*
*  •  *Mobile Solutions Consultant
*  •  *1-13 St Giles High Street, WC2H 8AG, London
  •  antoinebisch@google.com

<antoinebisch@google.com>


This email may be confidential and privileged. If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it has gone
to the wrong person.

The above terms reflect a potential business arrangement, are provided
solely as a basis for further discussion, and are not intended to be and do
not constitute a legally binding obligation. No legally binding obligations
will be created, implied, or inferred until an agreement in final form is
executed in writing by all parties involved.

**Comment by martinschierle** [comment]
Not sure if you really started this one given the problems with launching it. I just added in a naive stub for this (just current image on the upper left) for the time being (was touching some of that code anyway). Feel free to build on that and make it better, or to take another issue if you like.

**Comment by martinschierle** [comment]
A simple first version of this is in - closing for now.
