### ISSUE TITLE
Ship needs to maintain speed

### ISSUE THREAD

**Issue by martinschierle** [GoogleChromeLabs/performance-game#26]
Currently ship slows down quickly when not being accelerated. Originally (and physically) it needs to keep the speed it has.

**Comment by Svenmay** [comment]
I played around a bit with the code and I do think this behaviour is controlled by the property "drag".

Line 166: ship.body.drag.set(100);

Changing that to ship.body.drag.set(0); changes the game in such a way that the ships keeps the speed.

**Comment by Svenmay** [comment]
Submitted a fix.
