### ISSUE TITLE
Work on scoring mechanism

### ISSUE THREAD

**Issue by martinschierle** [GoogleChromeLabs/performance-game#5]
Right now highscore basically sums up destroyed asteroids, which isn't helpful. We need a scoring mechanism which fulfills two goals:
* It's limited by the page's performance (a well build site should in general be able to yield a higher score)
* It still reflects the player's game (bad player lower score, good player higher score)

**Comment by martinschierle** [comment]
After the last discussion it seems we keep the scoring, but don't save it. So we'll just show the score in the end, and let people share it with a link to the game. This will make it easier with respect to security/privacy stuff, we can also skip the db etc. We can still add real leaderboards in a later step, if people seem to like the game. So this ticket is rather about removing the old scoring stuff, and adapting the endscreen to the new model (show game score, show lighthouse score, link out to lighthouse report if possible, big sharing button in center)

**Comment by martinschierle** [comment]
The longer I think about it I'm tempted to completely rip out the scoring. This will give more highlight to the lighthouse scores, which are more important anyway. So the game itself would only be about winning or dying. Any thoughts?

**Comment by Svenmay** [comment]
My 2 cents: I do think a game needs a score. Without score it's no game, but just a different, interactive  "view" of the lighthouse report :-)

But I could understand the decision to remove the scoring to keep the whole project simpler for the moment.

**Comment by martinschierle** [comment]
In general I feel the same. Let's leave the score in as-is for now (removing would also add work). We can still extend (or rip out) later. Closing this for now.
